const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{fundo1: 0},
	{nome: 0},
	{Touch: 0},
	{cx1: 0},
	{historia1: 0},
	{historia2: 0},
	{caixaperguntas1: 0},
	{codigo: 0},
	{pergunta1: 0},
	{op1: 0},
	{op2: 0},
	{op3: 0},
	{cod: 0},
	{homem: 0},
	{balao: 0},
	{Text: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{tito: 0},
	{cx2n2: 0},
	{p1n2: 0},
	{fundon2: 0},
	{fundon1: 0},
	{quadro11: 0},
	{play: 0},
	{avancar: 0},
	{dica: 0},
	{Audio: 0},
	{Quadro: 0},
	{fundoantiguidade: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{caixatransicao: 0},
	{Video: 0},
	{Sprite6: 0},
	{Texto: 0},
	{Sprite7: 0},
	{Vídeo: 0},
	{Vídeo2: 0},
	{Sprite8: 0},
	{Vídeo3: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite13: 0},
	{Texto2: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{cavaleiro: 0},
	{Vídeo4: 0},
	{Sprite20: 0},
	{balao2: 0},
	{Text2: 0},
	{Quadro2: 0},
	{Quadro3: 0},
	{fundoF1: 0},
	{Sprite: 0},
	{robo: 0},
	{Sprite19: 0},
	{dr3: 0},
	{Sprite5: 0},
	{Video2: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{quadro12: 0},
	{quadro13: 0},
	{zito: 0},
	{Sprite2: 0},
	{fundo2: 0},
	{Sprite18: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Vídeo5: 0},
	{Vídeo6: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Sprite26: 0},
	{Pontos: 0}
];

self.InstanceType = {
	fundo1: class extends self.ISpriteInstance {},
	nome: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	cx1: class extends self.ISpriteInstance {},
	historia1: class extends self.ITextInstance {},
	historia2: class extends self.ITextInstance {},
	caixaperguntas1: class extends self.ISpriteInstance {},
	codigo: class extends self.ISpriteInstance {},
	pergunta1: class extends self.ITextInstance {},
	op1: class extends self.ITextInstance {},
	op2: class extends self.ITextInstance {},
	op3: class extends self.ITextInstance {},
	cod: class extends self.ITextInstance {},
	homem: class extends self.ISpriteInstance {},
	balao: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	tito: class extends self.ISpriteInstance {},
	cx2n2: class extends self.ISpriteInstance {},
	p1n2: class extends self.ISpriteInstance {},
	fundon2: class extends self.ISpriteInstance {},
	fundon1: class extends self.ISpriteInstance {},
	quadro11: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	avancar: class extends self.ISpriteInstance {},
	dica: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Quadro: class extends self.ISpriteInstance {},
	fundoantiguidade: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	caixatransicao: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Vídeo: class extends self.IWorldInstance {},
	Vídeo2: class extends self.IWorldInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Vídeo3: class extends self.IWorldInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	cavaleiro: class extends self.ISpriteInstance {},
	Vídeo4: class extends self.IWorldInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	balao2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Quadro2: class extends self.ISpriteInstance {},
	Quadro3: class extends self.ISpriteInstance {},
	fundoF1: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	robo: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	dr3: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	quadro12: class extends self.ISpriteInstance {},
	quadro13: class extends self.ISpriteInstance {},
	zito: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	fundo2: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Vídeo5: class extends self.IWorldInstance {},
	Vídeo6: class extends self.IWorldInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Sprite26: class extends self.ISpriteInstance {}
}